project:
  type: website

website:
  title: "Homepage"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/pthaotran/
      - icon: github
        href: https://github.com/tranphthao
format:
  html:
    theme: journal
    css: styles.css

editor: visual

