project:
  type: website

website:
  title: "The Garden of Gains"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tranphthao
      - icon: linkedin
        href: https://www.linkedin.com/in/pthaotran/
format:
  html:
    theme: journal
    css: styles.css

editor: visual

